package structs

type Coinbase struct {
	Data struct {
		Currency string `json:"currency"`
		Rates    struct {
			AED string `json:"AED"`
			AFN string `json:"AFN"`
			ALL string `json:"ALL"`
			AMD string `json:"AMD"`
			ANG string `json:"ANG"`
			AOA string `json:"AOA"`
			ARS string `json:"ARS"`
			AUD string `json:"AUD"`
			AWG string `json:"AWG"`
			AZN string `json:"AZN"`
			BAM string `json:"BAM"`
			BBD string `json:"BBD"`
			BDT string `json:"BDT"`
			BGN string `json:"BGN"`
			BHD string `json:"BHD"`
			BIF string `json:"BIF"`
			BMD string `json:"BMD"`
			BND string `json:"BND"`
			BOB string `json:"BOB"`
			BRL string `json:"BRL"`
			BSD string `json:"BSD"`
			BTC string `json:"BTC"`
			BTN string `json:"BTN"`
			BWP string `json:"BWP"`
			BYN string `json:"BYN"`
			BYR string `json:"BYR"`
			BZD string `json:"BZD"`
			CAD string `json:"CAD"`
			CDF string `json:"CDF"`
			CHF string `json:"CHF"`
			CLF string `json:"CLF"`
			CLP string `json:"CLP"`
			CNY string `json:"CNY"`
			COP string `json:"COP"`
			CRC string `json:"CRC"`
			CUC string `json:"CUC"`
			CVE string `json:"CVE"`
			CZK string `json:"CZK"`
			DJF string `json:"DJF"`
			DKK string `json:"DKK"`
			DOP string `json:"DOP"`
			DZD string `json:"DZD"`
			EEK string `json:"EEK"`
			EGP string `json:"EGP"`
			ERN string `json:"ERN"`
			ETB string `json:"ETB"`
			ETH string `json:"ETH"`
			EUR string `json:"EUR"`
			FJD string `json:"FJD"`
			FKP string `json:"FKP"`
			GBP string `json:"GBP"`
			GEL string `json:"GEL"`
			GGP string `json:"GGP"`
			GHS string `json:"GHS"`
			GIP string `json:"GIP"`
			GMD string `json:"GMD"`
			GNF string `json:"GNF"`
			GTQ string `json:"GTQ"`
			GYD string `json:"GYD"`
			HKD string `json:"HKD"`
			HNL string `json:"HNL"`
			HRK string `json:"HRK"`
			HTG string `json:"HTG"`
			HUF string `json:"HUF"`
			IDR string `json:"IDR"`
			ILS string `json:"ILS"`
			IMP string `json:"IMP"`
			INR string `json:"INR"`
			IQD string `json:"IQD"`
			ISK string `json:"ISK"`
			JEP string `json:"JEP"`
			JMD string `json:"JMD"`
			JOD string `json:"JOD"`
			JPY string `json:"JPY"`
			KES string `json:"KES"`
			KGS string `json:"KGS"`
			KHR string `json:"KHR"`
			KMF string `json:"KMF"`
			KRW string `json:"KRW"`
			KWD string `json:"KWD"`
			KYD string `json:"KYD"`
			KZT string `json:"KZT"`
			LAK string `json:"LAK"`
			LBP string `json:"LBP"`
			LKR string `json:"LKR"`
			LRD string `json:"LRD"`
			LSL string `json:"LSL"`
			LTC string `json:"LTC"`
			LTL string `json:"LTL"`
			LVL string `json:"LVL"`
			LYD string `json:"LYD"`
			MAD string `json:"MAD"`
			MDL string `json:"MDL"`
			MGA string `json:"MGA"`
			MKD string `json:"MKD"`
			MMK string `json:"MMK"`
			MNT string `json:"MNT"`
			MOP string `json:"MOP"`
			MRO string `json:"MRO"`
			MTL string `json:"MTL"`
			MUR string `json:"MUR"`
			MVR string `json:"MVR"`
			MWK string `json:"MWK"`
			MXN string `json:"MXN"`
			MYR string `json:"MYR"`
			MZN string `json:"MZN"`
			NAD string `json:"NAD"`
			NGN string `json:"NGN"`
			NIO string `json:"NIO"`
			NOK string `json:"NOK"`
			NPR string `json:"NPR"`
			NZD string `json:"NZD"`
			OMR string `json:"OMR"`
			PAB string `json:"PAB"`
			PEN string `json:"PEN"`
			PGK string `json:"PGK"`
			PHP string `json:"PHP"`
			PKR string `json:"PKR"`
			PLN string `json:"PLN"`
			PYG string `json:"PYG"`
			QAR string `json:"QAR"`
			RON string `json:"RON"`
			RSD string `json:"RSD"`
			RUB string `json:"RUB"`
			RWF string `json:"RWF"`
			SAR string `json:"SAR"`
			SBD string `json:"SBD"`
			SCR string `json:"SCR"`
			SEK string `json:"SEK"`
			SGD string `json:"SGD"`
			SHP string `json:"SHP"`
			SLL string `json:"SLL"`
			SOS string `json:"SOS"`
			SRD string `json:"SRD"`
			SSP string `json:"SSP"`
			STD string `json:"STD"`
			SVC string `json:"SVC"`
			SZL string `json:"SZL"`
			THB string `json:"THB"`
			TJS string `json:"TJS"`
			TMT string `json:"TMT"`
			TND string `json:"TND"`
			TOP string `json:"TOP"`
			TRY string `json:"TRY"`
			TTD string `json:"TTD"`
			TWD string `json:"TWD"`
			TZS string `json:"TZS"`
			UAH string `json:"UAH"`
			UGX string `json:"UGX"`
			USD string `json:"USD"`
			UYU string `json:"UYU"`
			UZS string `json:"UZS"`
			VEF string `json:"VEF"`
			VND string `json:"VND"`
			VUV string `json:"VUV"`
			WST string `json:"WST"`
			XAF string `json:"XAF"`
			XAG string `json:"XAG"`
			XAU string `json:"XAU"`
			XCD string `json:"XCD"`
			XDR string `json:"XDR"`
			XOF string `json:"XOF"`
			XPD string `json:"XPD"`
			XPF string `json:"XPF"`
			XPT string `json:"XPT"`
			YER string `json:"YER"`
			ZAR string `json:"ZAR"`
			ZMK string `json:"ZMK"`
			ZMW string `json:"ZMW"`
			ZWL string `json:"ZWL"`
		} `json:"rates"`
	} `json:"data"`
}
